### ISSUE TITLE
please fix it

### ISSUE THREAD

**Issue by ousun** [shiretu/crtmpserver#2]
I am compile crtmpserver wiht gcc6.1.1 and i get error:
/crtmpserver/sources/common/src/platform/linux/linuxplatform.cpp:271:8: error：invalid suffix on literal; C++11 requires a space between literal and string macro [-Werror=literal-suffix]
please fix it.

**Comment by nyetwurk** [comment]
Works fine with gcc-6.3
