### ISSUE TITLE
failed build with openssl 1.1...problems with crypto.cpp

### ISSUE THREAD

**Issue by gillecaluim** [shiretu/crtmpserver#7]
```
[ 19%] Building CXX object common/CMakeFiles/common.dir/build/crtmpserver/src/crtmpserver/sources/common/src/utils/misc/crypto.cpp.o
/build/crtmpserver/src/crtmpserver/sources/common/src/utils/misc/crypto.cpp: In member function ‘bool DHWrapper::Initialize()’:
/build/crtmpserver/src/crtmpserver/sources/common/src/utils/misc/crypto.cpp:49:6: error: invalid use of incomplete type ‘DH {aka struct dh_st}’
  _pDH->p = BN_new();
      ^~
In file included from /usr/include/openssl/bn.h:19:0,
                 from /build/crtmpserver/src/crtmpserver/sources/common/include/utils/misc/crypto.h:25,
                 from /build/crtmpserver/src/crtmpserver/sources/common/include/utils/buffering/iobuffer.h:27,
                 from /build/crtmpserver/src/crtmpserver/sources/common/include/utils/buffering/buffering.h:23,
                 from /build/crtmpserver/src/crtmpserver/sources/common/include/utils/utils.h:23,
                 from /build/crtmpserver/src/crtmpserver/sources/common/include/common.h:25:
/usr/include/openssl/ossl_typ.h:104:16: note: forward declaration of ‘DH {aka struct dh_st}’
 typedef struct dh_st DH;
                ^~~~~
/build/crtmpserver/src/crtmpserver/sources/common/src/utils/misc/crypto.cpp:49:8: error: invalid use of incomplete type ‘DH {aka struct dh_st}’
  _pDH->p = BN_new();
        ^
In file included from /usr/include/openssl/bn.h:19:0,
                 from /build/crtmpserver/src/crtmpserver/sources/common/include/utils/misc/crypto.h:25,
                 from /build/crtmpserver/src/crtmpserver/sources/common/include/utils/buffering/iobuffer.h:27,
                 from /build/crtmpserver/src/crtmpserver/sources/common/include/utils/buffering/buffering.h:23,
                 from /build/crtmpserver/src/crtmpserver/sources/common/include/utils/utils.h:23,
                 from /build/crtmpserver/src/crtmpserver/sources/common/include/common.h:25:
/usr/include/openssl/ossl_typ.h:104:16: note: forward declaration of ‘DH {aka struct dh_st}’
 typedef struct dh_st DH;
                ^~~~~
/build/crtmpserver/src/crtmpserver/sources/common/src/utils/misc/crypto.cpp:50:10: error: invalid use of incomplete type ‘DH {aka struct dh_st}’
  if (_pDH->p == NULL) {
          ^~
In file included from /usr/include/openssl/bn.h:19:0,
                 from /build/crtmpserver/src/crtmpserver/sources/common/include/utils/misc/crypto.h:25,
                 from /build/crtmpserver/src/crtmpserver/sources/common/include/utils/buffering/iobuffer.h:27,
                 from /build/crtmpserver/src/crtmpserver/sources/common/include/utils/buffering/buffering.h:23,
                 from /build/crtmpserver/src/crtmpserver/sources/common/include/utils/utils.h:23,
                 from /build/crtmpserver/src/crtmpserver/sources/common/include/common.h:25:
/usr/include/openssl/ossl_typ.h:104:16: note: forward declaration of ‘DH {aka struct dh_st}’
 typedef struct dh_st DH;
                ^~~~~
/build/crtmpserver/src/crtmpserver/sources/common/src/utils/misc/crypto.cpp:50:12: error: invalid use of incomplete type ‘DH {aka struct dh_st}’
  if (_pDH->p == NULL) {
            ^
In file included from /usr/include/openssl/bn.h:19:0,
                 from /build/crtmpserver/src/crtmpserver/sources/common/include/utils/misc/crypto.h:25,
                 from /build/crtmpserver/src/crtmpserver/sources/common/include/utils/buffering/iobuffer.h:27,
                 from /build/crtmpserver/src/crtmpserver/sources/common/include/utils/buffering/buffering.h:23,
                 from /build/crtmpserver/src/crtmpserver/sources/common/include/utils/utils.h:23,
                 from /build/crtmpserver/src/crtmpserver/sources/common/include/common.h:25:
/usr/include/openssl/ossl_typ.h:104:16: note: forward declaration of ‘DH {aka struct dh_st}’
 typedef struct dh_st DH;
                ^~~~~
/build/crtmpserver/src/crtmpserver/sources/common/src/utils/misc/crypto.cpp:55:6: error: invalid use of incomplete type ‘DH {aka struct dh_st}’
  _pDH->g = BN_new();
      ^~
In file included from /usr/include/openssl/bn.h:19:0,
                 from /build/crtmpserver/src/crtmpserver/sources/common/include/utils/misc/crypto.h:25,
                 from /build/crtmpserver/src/crtmpserver/sources/common/include/utils/buffering/iobuffer.h:27,
                 from /build/crtmpserver/src/crtmpserver/sources/common/include/utils/buffering/buffering.h:23,
                 from /build/crtmpserver/src/crtmpserver/sources/common/include/utils/utils.h:23,
                 from /build/crtmpserver/src/crtmpserver/sources/common/include/common.h:25:
/usr/include/openssl/ossl_typ.h:104:16: note: forward declaration of ‘DH {aka struct dh_st}’
 typedef struct dh_st DH;
                ^~~~~
/build/crtmpserver/src/crtmpserver/sources/common/src/utils/misc/crypto.cpp:55:8: error: invalid use of incomplete type ‘DH {aka struct dh_st}’
  _pDH->g = BN_new();
        ^
In file included from /usr/include/openssl/bn.h:19:0,
                 from /build/crtmpserver/src/crtmpserver/sources/common/include/utils/misc/crypto.h:25,
                 from /build/crtmpserver/src/crtmpserver/sources/common/include/utils/buffering/iobuffer.h:27,
                 from /build/crtmpserver/src/crtmpserver/sources/common/include/utils/buffering/buffering.h:23,
                 from /build/crtmpserver/src/crtmpserver/sources/common/include/utils/utils.h:23,
                 from /build/crtmpserver/src/crtmpserver/sources/common/include/common.h:25:
/usr/include/openssl/ossl_typ.h:104:16: note: forward declaration of ‘DH {aka struct dh_st}’
 typedef struct dh_st DH;
                ^~~~~
/build/crtmpserver/src/crtmpserver/sources/common/src/utils/misc/crypto.cpp:56:10: error: invalid use of incomplete type ‘DH {aka struct dh_st}’
  if (_pDH->g == NULL) {
          ^~
In file included from /usr/include/openssl/bn.h:19:0,
                 from /build/crtmpserver/src/crtmpserver/sources/common/include/utils/misc/crypto.h:25,
                 from /build/crtmpserver/src/crtmpserver/sources/common/include/utils/buffering/iobuffer.h:27,
                 from /build/crtmpserver/src/crtmpserver/sources/common/include/utils/buffering/buffering.h:23,
                 from /build/crtmpserver/src/crtmpserver/sources/common/include/utils/utils.h:23,
                 from /build/crtmpserver/src/crtmpserver/sources/common/include/common.h:25:
/usr/include/openssl/ossl_typ.h:104:16: note: forward declaration of ‘DH {aka struct dh_st}’
 typedef struct dh_st DH;
                ^~~~~
/build/crtmpserver/src/crtmpserver/sources/common/src/utils/misc/crypto.cpp:56:12: error: invalid use of incomplete type ‘DH {aka struct dh_st}’
  if (_pDH->g == NULL) {
            ^
In file included from /usr/include/openssl/bn.h:19:0,
                 from /build/crtmpserver/src/crtmpserver/sources/common/include/utils/misc/crypto.h:25,
                 from /build/crtmpserver/src/crtmpserver/sources/common/include/utils/buffering/iobuffer.h:27,
                 from /build/crtmpserver/src/crtmpserver/sources/common/include/utils/buffering/buffering.h:23,
                 from /build/crtmpserver/src/crtmpserver/sources/common/include/utils/utils.h:23,
                 from /build/crtmpserver/src/crtmpserver/sources/common/include/common.h:25:
/usr/include/openssl/ossl_typ.h:104:16: note: forward declaration of ‘DH {aka struct dh_st}’
 typedef struct dh_st DH;
                ^~~~~
/build/crtmpserver/src/crtmpserver/sources/common/src/utils/misc/crypto.cpp:63:21: error: invalid use of incomplete type ‘DH {aka struct dh_st}’
  if (BN_hex2bn(&_pDH->p, P1024) == 0) {
                     ^~
In file included from /usr/include/openssl/bn.h:19:0,
                 from /build/crtmpserver/src/crtmpserver/sources/common/include/utils/misc/crypto.h:25,
                 from /build/crtmpserver/src/crtmpserver/sources/common/include/utils/buffering/iobuffer.h:27,
                 from /build/crtmpserver/src/crtmpserver/sources/common/include/utils/buffering/buffering.h:23,
                 from /build/crtmpserver/src/crtmpserver/sources/common/include/utils/utils.h:23,
                 from /build/crtmpserver/src/crtmpserver/sources/common/include/common.h:25:
/usr/include/openssl/ossl_typ.h:104:16: note: forward declaration of ‘DH {aka struct dh_st}’
 typedef struct dh_st DH;
                ^~~~~
/build/crtmpserver/src/crtmpserver/sources/common/src/utils/misc/crypto.cpp:63:23: error: invalid use of incomplete type ‘DH {aka struct dh_st}’
  if (BN_hex2bn(&_pDH->p, P1024) == 0) {
                       ^
In file included from /usr/include/openssl/bn.h:19:0,
                 from /build/crtmpserver/src/crtmpserver/sources/common/include/utils/misc/crypto.h:25,
                 from /build/crtmpserver/src/crtmpserver/sources/common/include/utils/buffering/iobuffer.h:27,
                 from /build/crtmpserver/src/crtmpserver/sources/common/include/utils/buffering/buffering.h:23,
                 from /build/crtmpserver/src/crtmpserver/sources/common/include/utils/utils.h:23,
                 from /build/crtmpserver/src/crtmpserver/sources/common/include/common.h:25:
/usr/include/openssl/ossl_typ.h:104:16: note: forward declaration of ‘DH {aka struct dh_st}’
 typedef struct dh_st DH;
                ^~~~~
/build/crtmpserver/src/crtmpserver/sources/common/src/utils/misc/crypto.cpp:68:22: error: invalid use of incomplete type ‘DH {aka struct dh_st}’
  if (BN_set_word(_pDH->g, 2) != 1) {
                      ^~
In file included from /usr/include/openssl/bn.h:19:0,
                 from /build/crtmpserver/src/crtmpserver/sources/common/include/utils/misc/crypto.h:25,
                 from /build/crtmpserver/src/crtmpserver/sources/common/include/utils/buffering/iobuffer.h:27,
                 from /build/crtmpserver/src/crtmpserver/sources/common/include/utils/buffering/buffering.h:23,
                 from /build/crtmpserver/src/crtmpserver/sources/common/include/utils/utils.h:23,
                 from /build/crtmpserver/src/crtmpserver/sources/common/include/common.h:25:
/usr/include/openssl/ossl_typ.h:104:16: note: forward declaration of ‘DH {aka struct dh_st}’
 typedef struct dh_st DH;
                ^~~~~
/build/crtmpserver/src/crtmpserver/sources/common/src/utils/misc/crypto.cpp:68:24: error: invalid use of incomplete type ‘DH {aka struct dh_st}’
  if (BN_set_word(_pDH->g, 2) != 1) {
                        ^
In file included from /usr/include/openssl/bn.h:19:0,
                 from /build/crtmpserver/src/crtmpserver/sources/common/include/utils/misc/crypto.h:25,
                 from /build/crtmpserver/src/crtmpserver/sources/common/include/utils/buffering/iobuffer.h:27,
                 from /build/crtmpserver/src/crtmpserver/sources/common/include/utils/buffering/buffering.h:23,
                 from /build/crtmpserver/src/crtmpserver/sources/common/include/utils/utils.h:23,
                 from /build/crtmpserver/src/crtmpserver/sources/common/include/common.h:25:
/usr/include/openssl/ossl_typ.h:104:16: note: forward declaration of ‘DH {aka struct dh_st}’
 typedef struct dh_st DH;
                ^~~~~
/build/crtmpserver/src/crtmpserver/sources/common/src/utils/misc/crypto.cpp:75:6: error: invalid use of incomplete type ‘DH {aka struct dh_st}’
  _pDH->length = _bitsCount;
      ^~
In file included from /usr/include/openssl/bn.h:19:0,
                 from /build/crtmpserver/src/crtmpserver/sources/common/include/utils/misc/crypto.h:25,
                 from /build/crtmpserver/src/crtmpserver/sources/common/include/utils/buffering/iobuffer.h:27,
                 from /build/crtmpserver/src/crtmpserver/sources/common/include/utils/buffering/buffering.h:23,
                 from /build/crtmpserver/src/crtmpserver/sources/common/include/utils/utils.h:23,
                 from /build/crtmpserver/src/crtmpserver/sources/common/include/common.h:25:
/usr/include/openssl/ossl_typ.h:104:16: note: forward declaration of ‘DH {aka struct dh_st}’
 typedef struct dh_st DH;
                ^~~~~
/build/crtmpserver/src/crtmpserver/sources/common/src/utils/misc/crypto.cpp:75:8: error: invalid use of incomplete type ‘DH {aka struct dh_st}’
  _pDH->length = _bitsCount;
        ^~~~~~
In file included from /usr/include/openssl/bn.h:19:0,
                 from /build/crtmpserver/src/crtmpserver/sources/common/include/utils/misc/crypto.h:25,
                 from /build/crtmpserver/src/crtmpserver/sources/common/include/utils/buffering/iobuffer.h:27,
                 from /build/crtmpserver/src/crtmpserver/sources/common/include/utils/buffering/buffering.h:23,
                 from /build/crtmpserver/src/crtmpserver/sources/common/include/utils/utils.h:23,
                 from /build/crtmpserver/src/crtmpserver/sources/common/include/common.h:25:
/usr/include/openssl/ossl_typ.h:104:16: note: forward declaration of ‘DH {aka struct dh_st}’
 typedef struct dh_st DH;
                ^~~~~
/build/crtmpserver/src/crtmpserver/sources/common/src/utils/misc/crypto.cpp: In member function ‘bool DHWrapper::CopyPublicKey(uint8_t*, int32_t)’:
/build/crtmpserver/src/crtmpserver/sources/common/src/utils/misc/crypto.cpp:93:21: error: invalid use of incomplete type ‘DH {aka struct dh_st}’
  return CopyKey(_pDH->pub_key, pDst, dstLength);
                     ^~
In file included from /usr/include/openssl/bn.h:19:0,
                 from /build/crtmpserver/src/crtmpserver/sources/common/include/utils/misc/crypto.h:25,
                 from /build/crtmpserver/src/crtmpserver/sources/common/include/utils/buffering/iobuffer.h:27,
                 from /build/crtmpserver/src/crtmpserver/sources/common/include/utils/buffering/buffering.h:23,
                 from /build/crtmpserver/src/crtmpserver/sources/common/include/utils/utils.h:23,
                 from /build/crtmpserver/src/crtmpserver/sources/common/include/common.h:25:
/usr/include/openssl/ossl_typ.h:104:16: note: forward declaration of ‘DH {aka struct dh_st}’
 typedef struct dh_st DH;
                ^~~~~
/build/crtmpserver/src/crtmpserver/sources/common/src/utils/misc/crypto.cpp:93:23: error: invalid use of incomplete type ‘DH {aka struct dh_st}’
  return CopyKey(_pDH->pub_key, pDst, dstLength);
                       ^~~~~~~
In file included from /usr/include/openssl/bn.h:19:0,
                 from /build/crtmpserver/src/crtmpserver/sources/common/include/utils/misc/crypto.h:25,
                 from /build/crtmpserver/src/crtmpserver/sources/common/include/utils/buffering/iobuffer.h:27,
                 from /build/crtmpserver/src/crtmpserver/sources/common/include/utils/buffering/buffering.h:23,
                 from /build/crtmpserver/src/crtmpserver/sources/common/include/utils/utils.h:23,
                 from /build/crtmpserver/src/crtmpserver/sources/common/include/common.h:25:
/usr/include/openssl/ossl_typ.h:104:16: note: forward declaration of ‘DH {aka struct dh_st}’
 typedef struct dh_st DH;
                ^~~~~
/build/crtmpserver/src/crtmpserver/sources/common/src/utils/misc/crypto.cpp: In member function ‘bool DHWrapper::CopyPrivateKey(uint8_t*, int32_t)’:
/build/crtmpserver/src/crtmpserver/sources/common/src/utils/misc/crypto.cpp:102:21: error: invalid use of incomplete type ‘DH {aka struct dh_st}’
  return CopyKey(_pDH->priv_key, pDst, dstLength);
                     ^~
In file included from /usr/include/openssl/bn.h:19:0,
                 from /build/crtmpserver/src/crtmpserver/sources/common/include/utils/misc/crypto.h:25,
                 from /build/crtmpserver/src/crtmpserver/sources/common/include/utils/buffering/iobuffer.h:27,
                 from /build/crtmpserver/src/crtmpserver/sources/common/include/utils/buffering/buffering.h:23,
                 from /build/crtmpserver/src/crtmpserver/sources/common/include/utils/utils.h:23,
                 from /build/crtmpserver/src/crtmpserver/sources/common/include/common.h:25:
/usr/include/openssl/ossl_typ.h:104:16: note: forward declaration of ‘DH {aka struct dh_st}’
 typedef struct dh_st DH;
                ^~~~~
/build/crtmpserver/src/crtmpserver/sources/common/src/utils/misc/crypto.cpp:102:23: error: invalid use of incomplete type ‘DH {aka struct dh_st}’
  return CopyKey(_pDH->priv_key, pDst, dstLength);
                       ^~~~~~~~
In file included from /usr/include/openssl/bn.h:19:0,
                 from /build/crtmpserver/src/crtmpserver/sources/common/include/utils/misc/crypto.h:25,
                 from /build/crtmpserver/src/crtmpserver/sources/common/include/utils/buffering/iobuffer.h:27,
                 from /build/crtmpserver/src/crtmpserver/sources/common/include/utils/buffering/buffering.h:23,
                 from /build/crtmpserver/src/crtmpserver/sources/common/include/utils/utils.h:23,
                 from /build/crtmpserver/src/crtmpserver/sources/common/include/common.h:25:
/usr/include/openssl/ossl_typ.h:104:16: note: forward declaration of ‘DH {aka struct dh_st}’
 typedef struct dh_st DH;
                ^~~~~
/build/crtmpserver/src/crtmpserver/sources/common/src/utils/misc/crypto.cpp: In member function ‘void DHWrapper::Cleanup()’:
/build/crtmpserver/src/crtmpserver/sources/common/src/utils/misc/crypto.cpp:156:11: error: invalid use of incomplete type ‘DH {aka struct dh_st}’
   if (_pDH->p != NULL) {
           ^~
In file included from /usr/include/openssl/bn.h:19:0,
                 from /build/crtmpserver/src/crtmpserver/sources/common/include/utils/misc/crypto.h:25,
                 from /build/crtmpserver/src/crtmpserver/sources/common/include/utils/buffering/iobuffer.h:27,
                 from /build/crtmpserver/src/crtmpserver/sources/common/include/utils/buffering/buffering.h:23,
                 from /build/crtmpserver/src/crtmpserver/sources/common/include/utils/utils.h:23,
                 from /build/crtmpserver/src/crtmpserver/sources/common/include/common.h:25:
/usr/include/openssl/ossl_typ.h:104:16: note: forward declaration of ‘DH {aka struct dh_st}’
 typedef struct dh_st DH;
                ^~~~~
/build/crtmpserver/src/crtmpserver/sources/common/src/utils/misc/crypto.cpp:156:13: error: invalid use of incomplete type ‘DH {aka struct dh_st}’
   if (_pDH->p != NULL) {
             ^
In file included from /usr/include/openssl/bn.h:19:0,
                 from /build/crtmpserver/src/crtmpserver/sources/common/include/utils/misc/crypto.h:25,
                 from /build/crtmpserver/src/crtmpserver/sources/common/include/utils/buffering/iobuffer.h:27,
                 from /build/crtmpserver/src/crtmpserver/sources/common/include/utils/buffering/buffering.h:23,
                 from /build/crtmpserver/src/crtmpserver/sources/common/include/utils/utils.h:23,
                 from /build/crtmpserver/src/crtmpserver/sources/common/include/common.h:25:
/usr/include/openssl/ossl_typ.h:104:16: note: forward declaration of ‘DH {aka struct dh_st}’
 typedef struct dh_st DH;
                ^~~~~
/build/crtmpserver/src/crtmpserver/sources/common/src/utils/misc/crypto.cpp:157:16: error: invalid use of incomplete type ‘DH {aka struct dh_st}’
    BN_free(_pDH->p);
                ^~
In file included from /usr/include/openssl/bn.h:19:0,
                 from /build/crtmpserver/src/crtmpserver/sources/common/include/utils/misc/crypto.h:25,
                 from /build/crtmpserver/src/crtmpserver/sources/common/include/utils/buffering/iobuffer.h:27,
                 from /build/crtmpserver/src/crtmpserver/sources/common/include/utils/buffering/buffering.h:23,
                 from /build/crtmpserver/src/crtmpserver/sources/common/include/utils/utils.h:23,
                 from /build/crtmpserver/src/crtmpserver/sources/common/include/common.h:25:
/usr/include/openssl/ossl_typ.h:104:16: note: forward declaration of ‘DH {aka struct dh_st}’
 typedef struct dh_st DH;
                ^~~~~
/build/crtmpserver/src/crtmpserver/sources/common/src/utils/misc/crypto.cpp:157:18: error: invalid use of incomplete type ‘DH {aka struct dh_st}’
    BN_free(_pDH->p);
                  ^
In file included from /usr/include/openssl/bn.h:19:0,
                 from /build/crtmpserver/src/crtmpserver/sources/common/include/utils/misc/crypto.h:25,
                 from /build/crtmpserver/src/crtmpserver/sources/common/include/utils/buffering/iobuffer.h:27,
                 from /build/crtmpserver/src/crtmpserver/sources/common/include/utils/buffering/buffering.h:23,
                 from /build/crtmpserver/src/crtmpserver/sources/common/include/utils/utils.h:23,
                 from /build/crtmpserver/src/crtmpserver/sources/common/include/common.h:25:
/usr/include/openssl/ossl_typ.h:104:16: note: forward declaration of ‘DH {aka struct dh_st}’
 typedef struct dh_st DH;
                ^~~~~
/build/crtmpserver/src/crtmpserver/sources/common/src/utils/misc/crypto.cpp:158:8: error: invalid use of incomplete type ‘DH {aka struct dh_st}’
    _pDH->p = NULL;
        ^~
In file included from /usr/include/openssl/bn.h:19:0,
                 from /build/crtmpserver/src/crtmpserver/sources/common/include/utils/misc/crypto.h:25,
                 from /build/crtmpserver/src/crtmpserver/sources/common/include/utils/buffering/iobuffer.h:27,
                 from /build/crtmpserver/src/crtmpserver/sources/common/include/utils/buffering/buffering.h:23,
                 from /build/crtmpserver/src/crtmpserver/sources/common/include/utils/utils.h:23,
                 from /build/crtmpserver/src/crtmpserver/sources/common/include/common.h:25:
/usr/include/openssl/ossl_typ.h:104:16: note: forward declaration of ‘DH {aka struct dh_st}’
 typedef struct dh_st DH;
                ^~~~~
/build/crtmpserver/src/crtmpserver/sources/common/src/utils/misc/crypto.cpp:158:10: error: invalid use of incomplete type ‘DH {aka struct dh_st}’
    _pDH->p = NULL;
          ^
In file included from /usr/include/openssl/bn.h:19:0,
                 from /build/crtmpserver/src/crtmpserver/sources/common/include/utils/misc/crypto.h:25,
                 from /build/crtmpserver/src/crtmpserver/sources/common/include/utils/buffering/iobuffer.h:27,
                 from /build/crtmpserver/src/crtmpserver/sources/common/include/utils/buffering/buffering.h:23,
                 from /build/crtmpserver/src/crtmpserver/sources/common/include/utils/utils.h:23,
                 from /build/crtmpserver/src/crtmpserver/sources/common/include/common.h:25:
/usr/include/openssl/ossl_typ.h:104:16: note: forward declaration of ‘DH {aka struct dh_st}’
 typedef struct dh_st DH;
                ^~~~~
/build/crtmpserver/src/crtmpserver/sources/common/src/utils/misc/crypto.cpp:160:11: error: invalid use of incomplete type ‘DH {aka struct dh_st}’
   if (_pDH->g != NULL) {
           ^~
In file included from /usr/include/openssl/bn.h:19:0,
                 from /build/crtmpserver/src/crtmpserver/sources/common/include/utils/misc/crypto.h:25,
                 from /build/crtmpserver/src/crtmpserver/sources/common/include/utils/buffering/iobuffer.h:27,
                 from /build/crtmpserver/src/crtmpserver/sources/common/include/utils/buffering/buffering.h:23,
                 from /build/crtmpserver/src/crtmpserver/sources/common/include/utils/utils.h:23,
                 from /build/crtmpserver/src/crtmpserver/sources/common/include/common.h:25:
/usr/include/openssl/ossl_typ.h:104:16: note: forward declaration of ‘DH {aka struct dh_st}’
 typedef struct dh_st DH;
                ^~~~~
/build/crtmpserver/src/crtmpserver/sources/common/src/utils/misc/crypto.cpp:160:13: error: invalid use of incomplete type ‘DH {aka struct dh_st}’
   if (_pDH->g != NULL) {
             ^
In file included from /usr/include/openssl/bn.h:19:0,
                 from /build/crtmpserver/src/crtmpserver/sources/common/include/utils/misc/crypto.h:25,
                 from /build/crtmpserver/src/crtmpserver/sources/common/include/utils/buffering/iobuffer.h:27,
                 from /build/crtmpserver/src/crtmpserver/sources/common/include/utils/buffering/buffering.h:23,
                 from /build/crtmpserver/src/crtmpserver/sources/common/include/utils/utils.h:23,
                 from /build/crtmpserver/src/crtmpserver/sources/common/include/common.h:25:
/usr/include/openssl/ossl_typ.h:104:16: note: forward declaration of ‘DH {aka struct dh_st}’
 typedef struct dh_st DH;
                ^~~~~
/build/crtmpserver/src/crtmpserver/sources/common/src/utils/misc/crypto.cpp:161:16: error: invalid use of incomplete type ‘DH {aka struct dh_st}’
    BN_free(_pDH->g);
                ^~
In file included from /usr/include/openssl/bn.h:19:0,
                 from /build/crtmpserver/src/crtmpserver/sources/common/include/utils/misc/crypto.h:25,
                 from /build/crtmpserver/src/crtmpserver/sources/common/include/utils/buffering/iobuffer.h:27,
                 from /build/crtmpserver/src/crtmpserver/sources/common/include/utils/buffering/buffering.h:23,
                 from /build/crtmpserver/src/crtmpserver/sources/common/include/utils/utils.h:23,
                 from /build/crtmpserver/src/crtmpserver/sources/common/include/common.h:25:
/usr/include/openssl/ossl_typ.h:104:16: note: forward declaration of ‘DH {aka struct dh_st}’
 typedef struct dh_st DH;
                ^~~~~
/build/crtmpserver/src/crtmpserver/sources/common/src/utils/misc/crypto.cpp:161:18: error: invalid use of incomplete type ‘DH {aka struct dh_st}’
    BN_free(_pDH->g);
                  ^
In file included from /usr/include/openssl/bn.h:19:0,
                 from /build/crtmpserver/src/crtmpserver/sources/common/include/utils/misc/crypto.h:25,
                 from /build/crtmpserver/src/crtmpserver/sources/common/include/utils/buffering/iobuffer.h:27,
                 from /build/crtmpserver/src/crtmpserver/sources/common/include/utils/buffering/buffering.h:23,
                 from /build/crtmpserver/src/crtmpserver/sources/common/include/utils/utils.h:23,
                 from /build/crtmpserver/src/crtmpserver/sources/common/include/common.h:25:
/usr/include/openssl/ossl_typ.h:104:16: note: forward declaration of ‘DH {aka struct dh_st}’
 typedef struct dh_st DH;
                ^~~~~
/build/crtmpserver/src/crtmpserver/sources/common/src/utils/misc/crypto.cpp:162:8: error: invalid use of incomplete type ‘DH {aka struct dh_st}’
    _pDH->g = NULL;
        ^~
In file included from /usr/include/openssl/bn.h:19:0,
                 from /build/crtmpserver/src/crtmpserver/sources/common/include/utils/misc/crypto.h:25,
                 from /build/crtmpserver/src/crtmpserver/sources/common/include/utils/buffering/iobuffer.h:27,
                 from /build/crtmpserver/src/crtmpserver/sources/common/include/utils/buffering/buffering.h:23,
                 from /build/crtmpserver/src/crtmpserver/sources/common/include/utils/utils.h:23,
                 from /build/crtmpserver/src/crtmpserver/sources/common/include/common.h:25:
/usr/include/openssl/ossl_typ.h:104:16: note: forward declaration of ‘DH {aka struct dh_st}’
 typedef struct dh_st DH;
                ^~~~~
/build/crtmpserver/src/crtmpserver/sources/common/src/utils/misc/crypto.cpp:162:10: error: invalid use of incomplete type ‘DH {aka struct dh_st}’
    _pDH->g = NULL;
          ^
In file included from /usr/include/openssl/bn.h:19:0,
                 from /build/crtmpserver/src/crtmpserver/sources/common/include/utils/misc/crypto.h:25,
                 from /build/crtmpserver/src/crtmpserver/sources/common/include/utils/buffering/iobuffer.h:27,
                 from /build/crtmpserver/src/crtmpserver/sources/common/include/utils/buffering/buffering.h:23,
                 from /build/crtmpserver/src/crtmpserver/sources/common/include/utils/utils.h:23,
                 from /build/crtmpserver/src/crtmpserver/sources/common/include/common.h:25:
/usr/include/openssl/ossl_typ.h:104:16: note: forward declaration of ‘DH {aka struct dh_st}’
 typedef struct dh_st DH;
                ^~~~~
/build/crtmpserver/src/crtmpserver/sources/common/src/utils/misc/crypto.cpp: In function ‘void InitRC4Encryption(uint8_t*, uint8_t*, uint8_t*, RC4_KEY*, RC4_KEY*)’:
/build/crtmpserver/src/crtmpserver/sources/common/src/utils/misc/crypto.cpp:200:11: error: aggregate ‘HMAC_CTX ctx’ has incomplete type and cannot be defined
  HMAC_CTX ctx;
           ^~~
/build/crtmpserver/src/crtmpserver/sources/common/src/utils/misc/crypto.cpp:201:2: error: ‘HMAC_CTX_init’ was not declared in this scope
  HMAC_CTX_init(&ctx);
  ^~~~~~~~~~~~~
/build/crtmpserver/src/crtmpserver/sources/common/src/utils/misc/crypto.cpp:201:2: note: suggested alternative: ‘HMAC_CTX_new’
  HMAC_CTX_init(&ctx);
  ^~~~~~~~~~~~~
  HMAC_CTX_new
/build/crtmpserver/src/crtmpserver/sources/common/src/utils/misc/crypto.cpp:205:2: error: ‘HMAC_CTX_cleanup’ was not declared in this scope
  HMAC_CTX_cleanup(&ctx);
  ^~~~~~~~~~~~~~~~
/build/crtmpserver/src/crtmpserver/sources/common/src/utils/misc/crypto.cpp:205:2: note: suggested alternative: ‘HMAC_CTX_get_md’
  HMAC_CTX_cleanup(&ctx);
  ^~~~~~~~~~~~~~~~
  HMAC_CTX_get_md
/build/crtmpserver/src/crtmpserver/sources/common/src/utils/misc/crypto.cpp: In function ‘std::__cxx11::string md5(uint8_t*, uint32_t, bool)’:
/build/crtmpserver/src/crtmpserver/sources/common/src/utils/misc/crypto.cpp:223:13: error: aggregate ‘EVP_MD_CTX mdctx’ has incomplete type and cannot be defined
  EVP_MD_CTX mdctx;
             ^~~~~
/build/crtmpserver/src/crtmpserver/sources/common/src/utils/misc/crypto.cpp:230:2: error: ‘EVP_MD_CTX_cleanup’ was not declared in this scope
  EVP_MD_CTX_cleanup(&mdctx);
  ^~~~~~~~~~~~~~~~~~
/build/crtmpserver/src/crtmpserver/sources/common/src/utils/misc/crypto.cpp:230:2: note: suggested alternative: ‘EVP_MD_CTX_create’
  EVP_MD_CTX_cleanup(&mdctx);
  ^~~~~~~~~~~~~~~~~~
  EVP_MD_CTX_create
/build/crtmpserver/src/crtmpserver/sources/common/src/utils/misc/crypto.cpp: In function ‘void HMACsha256(const void*, uint32_t, const void*, uint32_t, void*)’:
/build/crtmpserver/src/crtmpserver/sources/common/src/utils/misc/crypto.cpp:262:11: error: aggregate ‘HMAC_CTX ctx’ has incomplete type and cannot be defined
  HMAC_CTX ctx;
           ^~~
/build/crtmpserver/src/crtmpserver/sources/common/src/utils/misc/crypto.cpp:263:2: error: ‘HMAC_CTX_init’ was not declared in this scope
  HMAC_CTX_init(&ctx);
  ^~~~~~~~~~~~~
/build/crtmpserver/src/crtmpserver/sources/common/src/utils/misc/crypto.cpp:263:2: note: suggested alternative: ‘HMAC_CTX_new’
  HMAC_CTX_init(&ctx);
  ^~~~~~~~~~~~~
  HMAC_CTX_new
/build/crtmpserver/src/crtmpserver/sources/common/src/utils/misc/crypto.cpp:267:2: error: ‘HMAC_CTX_cleanup’ was not declared in this scope
  HMAC_CTX_cleanup(&ctx);
  ^~~~~~~~~~~~~~~~
/build/crtmpserver/src/crtmpserver/sources/common/src/utils/misc/crypto.cpp:267:2: note: suggested alternative: ‘HMAC_CTX_get_md’
  HMAC_CTX_cleanup(&ctx);
  ^~~~~~~~~~~~~~~~
  HMAC_CTX_get_md
/build/crtmpserver/src/crtmpserver/sources/common/src/utils/misc/crypto.cpp: In function ‘void CleanupSSL()’:
/build/crtmpserver/src/crtmpserver/sources/common/src/utils/misc/crypto.cpp:401:20: error: ‘void ERR_remove_state(long unsigned int)’ is deprecated [-Werror=deprecated-declarations]
  ERR_remove_state(0);
                    ^
In file included from /usr/include/openssl/cterr.h:14:0,
                 from /usr/include/openssl/ct.h:19,
                 from /usr/include/openssl/ssl.h:31,
                 from /build/crtmpserver/src/crtmpserver/sources/common/include/utils/misc/crypto.h:28,
                 from /build/crtmpserver/src/crtmpserver/sources/common/include/utils/buffering/iobuffer.h:27,
                 from /build/crtmpserver/src/crtmpserver/sources/common/include/utils/buffering/buffering.h:23,
                 from /build/crtmpserver/src/crtmpserver/sources/common/include/utils/utils.h:23,
                 from /build/crtmpserver/src/crtmpserver/sources/common/include/common.h:25:
/usr/include/openssl/err.h:258:1: note: declared here
 DEPRECATEDIN_1_0_0(void ERR_remove_state(unsigned long pid))
 ^
cc1plus: all warnings being treated as errors
make[2]: *** [common/CMakeFiles/common.dir/build.make:591: common/CMakeFiles/common.dir/build/crtmpserver/src/crtmpserver/sources/common/src/utils/misc/crypto.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:231: common/CMakeFiles/common.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
==> ERROR: A failure occurred in build().
```

**Comment by ObjectBoxPC** [comment]
Duplicate of #6
